fix bg

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -52,14 +52,24 @@ jobs:
           kubectl set image deployment/flask-deployment-green flask-app=${{ github.event.client_payload.image }}
           kubectl rollout status deployment/flask-deployment-green
 
-      # Automated Testing (Optional)
-      - name: Run Unit Tests
+      - name: Get Green Deployment Info
         run: |
-          export PYTHONPATH=$(pwd)
-          pytest tests/  # Assuming your tests are in the "tests" directory
+          GREEN_DEPLOYMENT_SERVICE_IP=$(kubectl get service flask-service -o jsonpath='{.spec.clusterIP}')
+          GREEN_DEPLOYMENT_SERVICE_PORT=$(kubectl get service flask-service -o jsonpath='{.spec.ports[0].port}')
+          echo "GREEN_DEPLOYMENT_IP=$GREEN_DEPLOYMENT_SERVICE_IP" >> $GITHUB_ENV
+          echo "GREEN_DEPLOYMENT_SERVICE_PORT=$GREEN_DEPLOYMENT_SERVICE_PORT" >> $GITHUB_ENV
 
-      #  Consider adding additional automated testing steps here (e.g., integration tests)
+      - name: Trigger Status Check
+        run: |
+          curl -X GET http://$GREEN_DEPLOYMENT_SERVICE_IP:$GREEN_DEPLOYMENT_SERVICE_PORT/status -s | jq .status
 
+      - name: Check Status Response
+        run: |
+          if [ "$STATUS_RESPONSE" != "\"running\"" ]; then
+            echo "Status check failed. Expected 'running', got '$STATUS_RESPONSE'"
+            exit 1
+          fi
+      
 
       # Switch Traffic to Green
       - name: Switch Traffic to Green
